Dev
SoftRyzen-internship/phlebologist pull request #56
Opened 2023-10-16 11:32 UTC by Yana-Palam

Секція 9: Форма запису
Секція 7: Відгуки пацієнтів

2023-10-16 16:00 UTC, nadiakhoptiuk commented on components/AboutImage/AboutVideo.tsx
> +          width={256}
також поправити розміри

2023-10-16 16:10 UTC, nadiakhoptiuk commented on sections/About/About.tsx
> +          <div className="wrapper rounded-t-medium bg-white pb-[52px] pt-6 md:rounded-t-extraLarge md:pb-[76px] md:pt-10 xl:flex xl:items-baseline xl:gap-10 xl:rounded-t-max xl:pb-28 xl:pt-16">
на мобільній версії текст з іншої секції відображається над фото https://prnt.sc/z0_QY42TQwED

2023-10-16 16:17 UTC, nadiakhoptiuk commented on components/AboutCareer/AboutCareer.tsx
> +          <ul className="mt-5 list-none md:mt-8 md:grid md:grid-cols-2 md:gap-x-6 xl:block">
краще використовувати щось одне, а тут суміш - і gap, і margin-bottom між лішками

2023-10-16 16:31 UTC, nadiakhoptiuk commented on sections/Treatments/Treatments.tsx
> +                        md:rounded-t-extraLarge md:pb-[76px] md:pt-[40px]
не варто переносити рядки. якщо вони занадто довгі, то допоможе комбінація alt + z

2023-10-16 16:36 UTC, nadiakhoptiuk commented on sections/Treatments/Treatments.tsx
> +          <div className="w-full xl:absolute xl:bottom-[110px] xl:left-1/2 xl:-translate-x-1/2 ">
на таблеті розміщення табів не відповідає макету (фото вгорі повинно бути)

2023-10-16 16:41 UTC, nadiakhoptiuk commented on components/TreatmentTabList/TreatmentTabList.tsx
> +      <Tab.Panels>
перевірити відступи на десктопі
https://prnt.sc/lh0-j7UX1iuZ
https://prnt.sc/vI17ZwJA9ywr

2023-10-17 06:39 UTC, supermacchan commented on sections/Treatments/Treatments.tsx
> +          <div className="w-full xl:absolute xl:bottom-[110px] xl:left-1/2 xl:-translate-x-1/2 ">
Зміна позиціонування фото узгоджена із замовником, макет просто не перемальовували.

2023-10-17 06:43 UTC, supermacchan commented on components/TreatmentTabList/TreatmentTabList.tsx
> +      <Tab.Panels>
Там зараз заміняють контент, щоб контент встав в грід коректно. Це проблема з дизайном, який був промальований лише для одного з методів - в інших через іншу кількість контенту почало все повзти. На минулому тижні на мітингу я давала кілька варіантів позиціонування на вибір - разом зі Світланою та Валентиною зійшлися на тому, що залишаємо грід, а контент корегуємо, щоб кількість символів була однакова для всіх методів, тоді все встає коректно та відступи зберігаються, як на макеті. Новий контент для укр версії вже готовий (просто його немає в цьому пулі, він в окремій гілці), ще чекаю на правки англ контенту від Валентини.

2023-10-17 08:36 UTC, nadiakhoptiuk requested changes

2023-10-17 08:36 UTC, nadiakhoptiuk commented on sections/Banner/Banner.tsx
> +            <div className="flex flex-col md:flex-col-reverse md:items-end md:gap-6 xl:gap-12 xl:pr-[136px]">
зайвий правий падінг

2023-10-17 08:36 UTC, nadiakhoptiuk commented on components/Slider/Slider.tsx
>  import 'keen-slider/keen-slider.min.css';
стилі краще імпортувати в кінці (іноді через це навіть помилки бувають при білді)

2023-10-17 08:36 UTC, nadiakhoptiuk commented on components/Slider/Slider.tsx
>                />
варто додати spacing 29 для мобільного також, бо при гортанні всі слайди склеїлися один до одного

2023-10-17 08:36 UTC, nadiakhoptiuk commented on components/Feedbacks/FeedbackCap/FeedbackCap.tsx
> +    <div className="relative z-10 flex justify-between">
для цього діва рекомендую задати якийсь мінімальний gap, бо може бути ситуація, коли текст буде дуже близько до картинки: https://prnt.sc/EueWEbGYkVuE

2023-10-17 08:36 UTC, nadiakhoptiuk commented on components/Feedbacks/FeedbackCap/FeedbackCap.tsx
> +import setupDateFormat from '@/utils/setupDateFromat';
граматична помилка в назві файлу

2023-10-17 08:36 UTC, nadiakhoptiuk commented on components/Feedbacks/FeedbackSlide/FeedbackSlide.tsx
> +          <VideoPlayer data={data.video} isShown={isOpen} isReview />
перевірити висоту відео плеєра

мобільний, має бути 401px - https://prnt.sc/Kh4oIzmyNXEj
декстоп має бути 504 - https://prnt.sc/qz1e1DVDUIT9

2023-10-17 12:21 UTC, nadiakhoptiuk requested changes

2023-10-17 12:21 UTC, nadiakhoptiuk commented on components/FormInput/FormInput.props.ts
> +  register: any;
тут можна імпортувати з бібліотеки тип UseFormRegisterReturn

2023-10-17 12:21 UTC, nadiakhoptiuk commented on components/TreatmentQAItem/TreatmentQAItem.tsx
> +      <div className="md:ml-auto md:w-[319px] xl:w-auto">
на десктопі ширина 560

2023-10-17 12:21 UTC, nadiakhoptiuk commented on components/TreatmentQAItem/TreatmentQAItem.tsx
> +      <h3
для десктопа приміняється md:w-[320px] - не за макетом

2023-10-17 12:25 UTC, nadiakhoptiuk requested changes

2023-10-17 12:25 UTC, nadiakhoptiuk commented on middleware.ts
> -import Negotiator from 'negotiator';
negotiator потрібно видалити

2023-10-17 13:41 UTC, nadiakhoptiuk approved these changes

2023-10-17 13:42 UTC, merged